### ISSUE TITLE
Лишние слушатели

### ISSUE THREAD

**Issue by plusbpm** [derbyparty/racer-highway#8]
Не понятно назначение этого слушателя:
https://github.com/derbyparty/racer-highway/blob/master/lib/server/index.js#L150

backend никогда не вызывает событие connect, более того, он не даже не слушает события share agent
зато при каждом подключении вешается новый слушатель, а старый не снимается (нет обработки disconnect)
в итоге получаем:

```
(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Backend.addListener (events.js:239:17)
    at doneInitialization (/home/user/someproject/public_html/node_modules/racer-highway/lib/server/index.js:150:11)
    at WebSocketServer.<anonymous> (/home/user/someproject/public_html/node_modules/racer-highway/lib/server/index.js:101:5)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at /home/user/someproject/public_html/node_modules/racer-highway/lib/server/index.js:121:13
    at completeHybiUpgrade2 (/home/user/someproject/public_html/node_modules/racer-highway/node_modules/ws/lib/WebSocketServer.js:237:5)
    at completeHybiUpgrade1 (/home/user/someproject/public_html/node_modules/racer-highway/node_modules/ws/lib/WebSocketServer.js:262:13)
    at WebSocketServer.handleHybiUpgrade (/home/user/someproject/public_html/node_modules/racer-highway/node_modules/ws/lib/WebSocketServer.js:290:3)
    at WebSocketServer.handleUpgrade (/home/user/someproject/public_html/node_modules/racer-highway/node_modules/ws/lib/WebSocketServer.js:147:26)
    at next (/home/user/someproject/public_html/node_modules/racer-highway/lib/server/index.js:119:11)
    at MongoStore.<anonymous> (/home/user/someproject/public_html/node_modules/express-session/index.js:432:7)
    at MongoStore.tryCatcher (/home/user/someproject/public_html/node_modules/connect-mongo/node_modules/bluebird/js/release/util.js:11:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/user/someproject/public_html/node_modules/connect-mongo/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/user/someproject/public_html/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:543:21)
    at Promise._settlePromise0 (/home/user/someproject/public_html/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:591:10)
```

может я чего то не знаю ?

**Comment by maggnus** [comment]
Confirm. Same error...

**Comment by curran** [comment]
I'm also seeing the same error, although my stack trace looks slightly different

```
(node) warning: possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Backend.addListener (events.js:239:17)
    at doneInitialization (/Users/curran/repos/my-app/node_modules/racer-highway/lib/server/index.js:153:11)
    at WebSocketServer.<anonymous> (/Users/curran/repos/my-app/node_modules/racer-highway/lib/server/index.js:101:5)
    at emitOne (events.js:77:13)
    at WebSocketServer.emit (events.js:169:7)
    at /Users/curran/repos/my-app/node_modules/racer-highway/lib/server/index.js:121:13
    at completeHybiUpgrade2 (/Users/curran/repos/my-app/node_modules/ws/lib/WebSocketServer.js:237:5)
    at completeHybiUpgrade1 (/Users/curran/repos/my-app/node_modules/ws/lib/WebSocketServer.js:262:13)
    at WebSocketServer.handleHybiUpgrade (/Users/curran/repos/my-app/node_modules/ws/lib/WebSocketServer.js:290:3)
    at WebSocketServer.handleUpgrade (/Users/curran/repos/my-app/node_modules/ws/lib/WebSocketServer.js:147:26)
```

I wonder if there is some logic to remove these listeners periodically, but we are just not giving enough time for it to take effect?

**Comment by plusbpm** [comment]
No, the problem at the level of transport, subscriptions to documents has nothing to do with it.
I used the transport in a single project, but first remove these extra lines, without them normally works.

**Comment by curran** [comment]
I wonder if this happens only when using WebSockets, or also happens when using Browserchannel only. I'd like to test this but I'm not sure how to specify to not use WebSockets. Looking through https://github.com/derbyparty/racer-highway/blob/master/lib/server/index.js but not finding the anwser.

**Comment by plusbpm** [comment]
The problem is, in both cases.
Disable websocket you can:
```
handlers = racerHighway store, {session: session}, {browserChannelOnly:true}
```

**Comment by curran** [comment]
Thank you for the `browserChannelOnly` option. Is that documented somewhere? I want to learn Derby but struggling to find good documentation / tutorials.

After I use the `browserChannelOnly` option, I'm no longer getting the error after refreshing the page 30 times in 30 seconds. This solves the issue for me.

**Comment by plusbpm** [comment]
Client options are not documented, but they can be seen in the code:
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L6
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L12
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L35
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L73
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L84
https://github.com/derbyparty/racer-highway/blob/master/lib/browser/socket.js#L84

**Comment by plusbpm** [comment]
> After I use the browserChannelOnly option, I'm no longer getting the error after refreshing the page 30 times in 30 seconds. This solves the issue for me.

It may work with one client, but as soon as they will be more than 10, the error reappear.

**Comment by curran** [comment]
Ah ok. Yes, I'm testing with just a single client.

Thank you for the options references.
